#! /bin/bash

# ##### BEGIN LICENSE BLOCK #####
#
# "BakeMaster" Blender Add-on (version 3.0.0)
# Copyright (C) 2023 Kiril Strezikozin aka kemplerart
#
# This License permits you to use this software for any purpose including
# personal, educational, and commercial; You are allowed to modify it to suit
# your needs, and to redistribute the software or any modifications you make
# to it, as long as you follow the terms of this License and the
# GNU General Public License as published by the Free Software Foundation,
# either version 3 of the License, or (at your option) any later version.
#
# This License grants permission to redistribute this software to
# UNLIMITED END USER SEATS (OPEN SOURCE VARIANT) defined by the
# acquired License type. A redistributed copy of this software
# must follow and share similar rights of free software and usage
# specifications determined by the GNU General Public License.
#
# This program is free software and is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License in
# GNU.txt file along with this program. If not,
# see <http://www.gnu.org/licenses/>.
#
# ##### END LICENSE BLOCK #####


# Minimal bash file for addon's dev commands execution

# Sync non-version-dependant files
# (copy those files from the given path into the current directory)
# Example: ./commands sync-files-from path/to/dir
if [[ "$1" == "sync-files-from" ]]; then
    FROM_DIR=$2 

    # cp $FROM_DIR/.git/ ./.git/
    # cp $FROM_DIR/.github/ ./.github/
    cp $FROM_DIR/.vscode/ ./.vscode/

    # cp $FROM_DIR/addon/bakers/ ./addon/bakers/
    # cp $FROM_DIR/addon/utils/ ./addon/utils/
    cp $FROM_DIR/addon/README.txt ./addon/
    cp $FROM_DIR/addon/__init__.py ./addon/
    # cp $FROM_DIR/addon/labels.py ./addon/
    # cp $FROM_DIR/addon/operator_bake.py ./addon/
    cp $FROM_DIR/addon/operators.py ./addon/
    cp $FROM_DIR/addon/presets.py ./addon/
    cp $FROM_DIR/addon/properties.py ./addon/
    cp $FROM_DIR/addon/ui_base.py ./addon/
    cp $FROM_DIR/addon/ui_panels.py ./addon/

    # cp $FROM_DIR/docs/ ./docs/
    # cp $FROM_DIR/install/ ./install/
    cp $FROM_DIR/prefs/ ./prefs/
    cp $FROM_DIR/tests/ ./tests/
    # cp $FROM_DIR/commands ./
    cp $FROM_DIR/.gitignore ./
    cp $FROM_DIR/LICENSE ./
    cp $FROM_DIR/README.md ./
    cp $FROM_DIR/__init__.py ./
fi

# Run tests
# Example: ./commands run-tests path/to/set_of_tests.py
if [[ "$1" == "run-tests" ]]; then
    PYTHON_BIN=${PYTHON_BIN:-python3}

    # check if PYTHON_BIN binary is availble
    if ! command -v "${PYTHON_BIN}" > /dev/null; then
        echo "Error: Cannot find ${PYTHON_BIN} binary."
        exit 1
    fi

    python_bin=$(command -v "${PYTHON_BIN}")
    $python_bin $2
fi

exit 0
