#! /bin/bash

# ##### BEGIN GPL LICENSE BLOCK #####
#
# "BakeMaster" Add-on
# Copyright (C) 2023 Kiril Strezikozin aka kemplerart
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTIBILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# ##### END GPL LICENSE BLOCK #####


# Minimal bash file for addon's dev commands execution

# Sync non-version-dependant files
# (copy those files from the given path into the current directory)
# Example: ./run sync-files path/to/dir
if [[ "$1" == "sync-files" ]]; then
    FROM_DIR=$2 
    cp $FROM_DIR/.gitignore ./
    cp $FROM_DIR/LICENSE ./
    cp $FROM_DIR/README.md ./
    cp $FROM_DIR/README.txt ./
    cp $FROM_DIR/__init__.py ./
    cp $FROM_DIR/operators.py ./
    cp $FROM_DIR/presets.py ./
    cp $FROM_DIR/properties.py ./
    cp $FROM_DIR/ui_panel.py ./
    cp $FROM_DIR/ui_panel_base.py ./
    cp $FROM_DIR/utils.py ./
    cp $FROM_DIR/utils_bm_gets.py ./
fi

